### ISSUE TITLE
Base the module on regex rather than re?

### ISSUE THREAD

**Issue by ncoghlan** [cypreess/python-rex#6]
The regex project (https://pypi.python.org/pypi/regex) offers many improvements over the standard library's re module, and may be a better foundation than the standard library version.

However, since regex includes C extensions, it would pose some additional distribution challenges over the current pure Python approach in rex: https://code.google.com/p/mrab-regex-hg/issues/detail?id=84

**Comment by cypreess** [comment]
Thank you for your comment. However I am affraid of the compatiblity issues, as regex brings some different behaviours. The new commers would not only get used to rex API, but also to regex-module specific differences.

Can you point out some extraordinary features that would compensate problems with compatibliity issues and packaging problems?

**Comment by ncoghlan** [comment]
I suspect the additional distribution headaches arising from the regex C extensions are already enough hassle to mean it wouldn't be worth it, but some notable feature additions relative to the standard library re module are:
- Partial matches (for as-you-go validation of user input)
- Fuzzy matches (allowing some tolerance for errors in the text being scanned)
- Named option lists
- Checking against Unicode code point properties
- Named character classes

While I still think it's an interesting idea, it's probably best to stick with the existing standard library re module until regex has actually been proposed for inclusion in the standard library put through the PEP process.
